import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{backgroundColor: "lightblue", color: "black"}}>
          <p>Marketing Header</p>
        </header>
        <main style={{backgroundColor: "orange", color: "black"}}>{children}</main>
        <footer style={{backgroundColor: "brown", color: "white"}}>
          <p>Marketing Footer</p>
        </footer>
      </body>
    </html>
  );
}
